### ISSUE TITLE
Issue with year validation

### ISSUE THREAD

**Issue by admiralAwkbar** [github-services-engineering/services-demo-book-app#3]
I noticed that the "Create Book" form allows you enter invalid values for "`Year published`":

![Date isn't validated](https://cloud.githubusercontent.com/assets/4215/26662857/e2a53f0a-4654-11e7-9d97-dd1a52cf3ba4.png)

Can we add a validation to make sure that doesn't happen?

I think we should make sure we update our tests (in [`/spec/features/books_spec.rb`](https://github.com/github-services-engineering/services-demo-book-app/blob/master/spec/features/books_spec.rb)), then just add a model validation in [`/app/models/book.rb`](https://github.com/github-services-engineering/services-demo-book-app/blob/master/app/models/book.rb).

**Comment by IAmHughes** [comment]
@admiralAwkbar those links 404'd for me. I have the following working:

* [/spec/features/books_spec.rb](https://github.com/github-services-engineering/services-demo-book-app/blob/master/spec/features/books_spec.rb)
* [/app/models/book.rb](https://github.com/github-services-engineering/services-demo-book-app/blob/master/app/models/book.rb)

**Comment by stoe** [comment]
I'm going to grab this and fix it during an onsite demo today.
